version: '3'
services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data-volume:/data/db
    ports:
      - '4002:27017'
    logging:
      driver: none
  web-server:
    build:
      context: ./
      dockerfile: web_server/dockerfile
    ports:
      - '4000:4000'

      #THIS IS MY DOMAIN PEASANT
      #BEGONE THOT
  data-server:
    build:
      context: data_server/
      dockerfile: dockerfile
    ports:
      - '4001:4001'
volumes:
  data-volume: